### ISSUE TITLE
Research server

### ISSUE THREAD

**Issue by GewoonMaarten** [Gemeente-DenHaag/mijngemeente-gateway#1]
As a **developer** I want some knowledge about the architecture of the gateway, so that I can start implementing it. 

The goal is to research and document all the necessary frameworks such that these can be implemented in story #2  and subsequent stories. 

**Acceptance Criterion**:
- [ ] Researched server library for nodejs.
- [ ] Research hosting. Where is the server supposed to be hosted? Does that bring any advantages we can use?
- [ ] Researched logging system. Also depends on the hosting.
- [ ] Researched unit testing framework.
- [ ] Researched secure file upload (eg. max file size, whitelisted extensions, av scanner, filename limit, etc.)
- [ ] Researched secure BSN storage (eg. encryption, store in nodejs or external server like redis?)

**Comment by ogjtech** [comment]
> The goal is to research and document all the necessary frameworks such that these can be implemented in story #2 and subsequent stories.

This is like researching Agile so that you can then implement in waterfall. Rather than cramming all this research into one big story, research it as you get to the story. Researching everything first could lead to unexpected faults or misconceptions later on. We should research and set up an abstraction layer in the API's architecture, then research and implement functionality as development goes along.

A story like this is inherently not agile and invites nasty bugs and faults over time.

**Comment by GewoonMaarten** [comment]
Okay, I'll combine this with other stories.
