### ISSUE TITLE
Get all "zaken" for a given BSN

### ISSUE THREAD

**Issue by GewoonMaarten** [Gemeente-DenHaag/mijngemeente-gateway#5]
As a **user** I want to be able get all my _"zaken"_. This forwards the request to relevant [OpenZaak endpoint](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/VNG-Realisatie/zaken-api/1.1.0/src/openapi.yaml#/zaken/zaak_list).

**Out of scope**
- Unit tests and logging

**Depends on:**
- #2 Basic ExpressJS server

**Acceptance criteria**:
- [x] Mimic the functionality of the [FE gateway](https://dev.azure.com/mijndenhaag/mdh/_git/lopende_zaken?path=%2Fgateway%2Fsrc%2Fmain%2Fjava%2Fnl%2Fdenhaag%2Fpwapoc%2Fgateway%2FGatewayApplication.java&version=GBmaster&line=77&lineEnd=104&lineStartColumn=1&lineEndColumn=3&lineStyle=plain&_a=contents).
- [x] Endpoint should be a 1:1 mapping with the OpenZaak endpoint
- [x] Backend OpenZaak url should not be hardcoded (environment)

**Comment by ogjtech** [comment]
> As a developer I want to be able get all "zaken", so that I can provide it to the user.

State why the user wants this functionality, not why a developer is making it.

Why is the UUID now a BSN? Why are all "zaken" returned based on a BSN but a specific one is based on a UUID? Why not both? Filtering all results on a BSN instead of a user's UUID (or GUID) is probably a bad idea. A BSN can be used as an authentication method, but should not (also) be used as a filter. A 9-digit number is not unique enough and can lead to confusing results if filters are not defined properly.

**Comment by bddjong** [comment]
@ogjtech Users receive a JWT after authenticating with their BSN. The token contains their BSN and the gateway extracts it, and fills it in when making a request to OpenZaak. the GET /zaken endpoint has a query parameter for the BSN, along with a whole lot of other query parameters. We won't need to implement the filtering.
